/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docs: [
    "introduction",
    "roadmap",
    "tokenomics",
    {
      type: "category",
      label: "Developers",
      items: [
        "developers/deploy-first-app",
        "developers/llm-on-acurast",
        "developers/deployment-runtime-environment",
        "developers/on-demand-deployments",
      ],
      collapsed: true,
    },
    {
      type: "category",
      label: "Processors",
      items: [
        {
          type: "doc",
          id: "processors/become-compute-provider",
          label: "Become a Compute Provider",
        },
        "processors/multiple-processors",
        "processors/acurast-processors",
        "processors/rewards",
        "processors/benchmarks",
      ],
      collapsed: true,
    },
    {
      type: "category",
      label: "Staked Compute",
      items: [
        "staked-compute/overview",
        "staked-compute/how-to-stake",
        "staked-compute/staking-mechanics",
        "staked-compute/slashing",
        "staked-compute/mainnet-vs-canary",
        "staked-compute/staking-faq",
        "staked-compute/staking-glossary",
      ],
      collapsed: true,
    },
    {
      type: "category",
      label: "Acurast Protocol",
      items: [
        "acurast-orchestrator",

        {
          type: "category",
          label: "Architecture",
          items: [
            "acurast-protocol/architecture/architecture",
            "acurast-protocol/architecture/end-to-end",
            "acurast-protocol/architecture/application-layer",
            "acurast-protocol/architecture/execution-layer",
            "acurast-protocol/architecture/consensus-layer",
            "acurast-protocol/architecture/instances",
          ],
          collapsed: true,
        },
        "acurast-protocol/node-setup",
        "integrations",
        "networks",
        "audits",
        "whitepapers",
      ],
      collapsed: false,
    },
    {
      type: "category",
      label: "Token",
      items: [
        {
          type: "doc",
          id: "acurast-token",
          label: "Acurast Token",
        },
        {
          type: "doc",
          id: "token/claiming-acu",
          label: "Claiming Vested ACU",
        },
      ],
      collapsed: true,
    },
    {
      type: "category",
      label: "Wallets",
      items: [
        {
          type: "doc",
          id: "wallets/wallet-overview",
          label: "Overview",
        },
        {
          type: "doc",
          id: "wallets/wallets-airgap",
          label: "AirGap",
        },
        "wallets/wallets-talisman",
        {
          type: "doc",
          id: "wallets/wallets-subwallet",
          label: "SubWallet",
        },
        {
          type: "doc",
          id: "wallets/wallets-ledger",
          label: "Ledger (coming soon)",
        },
      ],
      collapsed: true,
    },
    {
      type: "category",
      label: "From Canary To Mainnet",
      items: [
        {
          type: "doc",
          id: "from-canary-to-mainnet/overview",
          label: "Overview",
        },
        {
          type: "doc",
          id: "from-canary-to-mainnet/token-transfers",
          label: "Transfers on Canary",
        },
      ],
      collapsed: true,
    },
    "faq",
    {
      type: "category",
      label: "Post-Mortems",
      items: [
        "post-mortem/2026-01-27-airdrop",
      ],
      collapsed: true,
    },
  ],
};

module.exports = sidebars;
